# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#cursor
cursor {
    default_monitor =
    no_hardware_cursors = false
    hotspot_padding = 1
    inactive_timeout = 0
    no_warps = false
    zoom_factor = 1.0
    zoom_rigid = false
    enable_hyprcursor = true
}

# Set cursor theme - this applies on reload unlike env variables
$cursorTheme = Bibata-Modern-Classic
$cursorSize = 24
exec = hyprctl setcursor $cursorTheme $cursorSize

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
